# -*- coding: utf-8 -*-
"""Feature Engineering.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KN1luidB3oBhZwUiNJ-Ke_15fDE8h7jn

## 1. Imports
"""

import pandas as pd
import numpy as np
from google.colab import drive

"""## 2. Mount Google Drive"""

drive.mount('/content/drive')

"""## 3. DataLoader"""

class DataLoader:
    """Loads all Olist CSV datasets from Google Drive."""

    BASE_PATH = '/content/drive/MyDrive/Project/'

    FILES = {
        'orders':               'olist_orders_dataset.csv',
        'order_items':          'olist_order_items_dataset.csv',
        'customers':            'olist_customers_dataset.csv',
        'sellers':              'olist_sellers_dataset.csv',
        'products':             'olist_products_dataset.csv',
        'geolocation':          'olist_geolocation_dataset.csv',
        'category_translation': 'product_category_name_translation.csv',
    }

    def load(self) -> dict[str, pd.DataFrame]:
        """Load all datasets and return as a dict keyed by name."""
        data = {}
        for name, filename in self.FILES.items():
            path = self.BASE_PATH + filename
            data[name] = pd.read_csv(path)
            print(f'  ✔ Loaded {name:25s} → {data[name].shape}')
        return data

"""## 4. DataPreprocessor"""

class DataPreprocessor:
    """Converts date columns and creates time-based features."""

    DATE_COLS = [
        'order_purchase_timestamp',
        'order_approved_at',
        'order_delivered_carrier_date',
        'order_delivered_customer_date',
        'order_estimated_delivery_date',
    ]

    def convert_dates(self, orders: pd.DataFrame) -> pd.DataFrame:
        """Cast all date columns to datetime."""
        for col in self.DATE_COLS:
            orders[col] = pd.to_datetime(orders[col])
        return orders

    def create_time_features(self, orders: pd.DataFrame) -> pd.DataFrame:
        """Derive approval_delay, estimated_delivery_time, day-of-week, hour."""
        orders['approval_delay'] = (
            orders['order_approved_at'] - orders['order_purchase_timestamp']
        ).dt.days

        orders['estimated_delivery_time'] = (
            orders['order_estimated_delivery_date'] - orders['order_purchase_timestamp']
        ).dt.days

        orders['purchase_day_of_week'] = orders['order_purchase_timestamp'].dt.dayofweek
        orders['purchase_hour']        = orders['order_purchase_timestamp'].dt.hour
        return orders

    def create_target(self, orders: pd.DataFrame) -> pd.DataFrame:
        """Binary target: 1 if delivered after estimated date, else 0."""
        orders['is_delayed'] = (
            orders['order_delivered_customer_date'] >
            orders['order_estimated_delivery_date']
        ).astype(int)
        return orders

    def fit_transform(self, orders: pd.DataFrame) -> pd.DataFrame:
        """Run the full preprocessing pipeline on orders."""
        orders = self.convert_dates(orders)
        orders = self.create_time_features(orders)
        orders = self.create_target(orders)
        return orders

"""## 5. OrderFeatureBuilder"""

class OrderFeatureBuilder:
    """Aggregates order_items to order-level features."""

    def build(self, order_items: pd.DataFrame) -> pd.DataFrame:
        """Return a DataFrame with total_items, total_price, total_freight_value."""
        agg = order_items.groupby('order_id').agg(
            total_items         =('order_item_id', 'count'),
            total_price         =('price',         'sum'),
            total_freight_value =('freight_value', 'sum'),
        ).reset_index()
        return agg

"""## 6. CategoryMapper"""

class CategoryMapper:
    """Maps fine-grained product categories to broad category groups."""

    CATEGORY_MAP: dict[str, list[str]] = {
        'electronics':    ['electronics', 'computers', 'computers_accessories',
                           'telephony', 'fixed_telephony', 'tablets_printing_image',
                           'audio', 'cine_photo', 'consoles_games'],
        'home':           ['furniture_decor', 'furniture_bedroom', 'furniture_living_room',
                           'furniture_mattress_and_upholstery', 'home_confort',
                           'home_comfort_2', 'home_appliances', 'home_appliances_2',
                           'kitchen_dining_laundry_garden_furniture',
                           'bed_bath_table', 'housewares'],
        'fashion':        ['fashion_shoes', 'fashion_bags_accessories',
                           'fashion_underwear_beach', 'fashion_male_clothing',
                           'fashio_female_clothing', 'fashion_childrens_clothes',
                           'fashion_sport'],
        'sports_toys':    ['sports_leisure', 'toys'],
        'health_beauty':  ['health_beauty', 'perfumery', 'diapers_and_hygiene'],
        'books':          ['books_general_interest', 'books_technical', 'books_imported'],
        'food':           ['food', 'food_drink', 'drinks'],
        'construction':   ['construction_tools_construction', 'construction_tools_safety',
                           'construction_tools_lights', 'costruction_tools_tools',
                           'costruction_tools_garden', 'home_construction'],
        'automotive':     ['auto'],
        'pet':            ['pet_shop'],
        'office':         ['office_furniture', 'stationery'],
        'industry':       ['industry_commerce_and_business', 'agro_industry_and_commerce',
                           'market_place'],
        'entertainment':  ['art', 'arts_and_craftmanship', 'music',
                           'cds_dvds_musicals', 'dvds_blu_ray', 'musical_instruments'],
        'garden':         ['garden_tools', 'flowers'],
        'lifestyle':      ['luggage_accessories', 'watches_gifts', 'cool_stuff'],
    }

    def __init__(self):
        # Build reverse lookup: category_name → group
        self._lookup: dict[str, str] = {}
        for group, cats in self.CATEGORY_MAP.items():
            for cat in cats:
                self._lookup[cat] = group

    @staticmethod
    def _clean_category(col: pd.Series) -> pd.Series:
        """Normalise category strings: lowercase, strip, replace spaces, ASCII."""
        return (
            col.astype(str)
               .str.strip()
               .str.lower()
               .str.replace(' ', '_')
               .str.normalize('NFKD')
               .str.encode('ascii', errors='ignore')
               .str.decode('utf-8')
        )

    def map_category(self, cat: str) -> str:
        """Return the broad group for a single category string."""
        return self._lookup.get(cat, 'other')

    def transform(self, df: pd.DataFrame,
                  products: pd.DataFrame,
                  category_translation: pd.DataFrame) -> pd.DataFrame:
        """Clean categories, merge translations, add category_group column."""
        products = products.copy()
        category_translation = category_translation.copy()

        products['product_category_name'] = self._clean_category(
            products['product_category_name'])
        category_translation['product_category_name'] = self._clean_category(
            category_translation['product_category_name'])

        df = df.merge(category_translation, on='product_category_name', how='left')
        df['product_category_name_english'] = (
            df['product_category_name_english'].fillna('unknown')
        )
        df['category_group'] = df['product_category_name_english'].apply(
            self.map_category)
        return df

"""## 7. GeoFeatureBuilder"""

class GeoFeatureBuilder:
    """Adds geographic features: lat/lng, Haversine distance, same-city/state flags."""

    @staticmethod
    def _haversine(lat1: pd.Series, lon1: pd.Series,
                   lat2: pd.Series, lon2: pd.Series) -> pd.Series:
        """Vectorised Haversine distance in km."""
        R = 6_371
        lat1, lon1, lat2, lon2 = map(np.radians, [lat1, lon1, lat2, lon2])
        dlat = lat2 - lat1
        dlon = lon2 - lon1
        a = np.sin(dlat / 2) ** 2 + np.cos(lat1) * np.cos(lat2) * np.sin(dlon / 2) ** 2
        return 2 * R * np.arcsin(np.sqrt(a))

    def _clean_geo(self, geolocation: pd.DataFrame) -> pd.DataFrame:
        """Average lat/lng per zip-code prefix."""
        return (
            geolocation
            .groupby('geolocation_zip_code_prefix')
            .agg(geolocation_lat=('geolocation_lat', 'mean'),
                 geolocation_lng=('geolocation_lng', 'mean'))
            .reset_index()
        )

    def build(self, df: pd.DataFrame, geolocation: pd.DataFrame) -> pd.DataFrame:
        """Attach customer & seller coordinates, compute distance and location flags."""
        geo = self._clean_geo(geolocation)

        # Customer geo
        df = df.merge(geo,
                      left_on='customer_zip_code_prefix',
                      right_on='geolocation_zip_code_prefix',
                      how='left')
        df.rename(columns={'geolocation_lat': 'customer_lat',
                            'geolocation_lng': 'customer_lng'}, inplace=True)
        df.drop(columns=['geolocation_zip_code_prefix'], inplace=True)

        # Seller geo
        df = df.merge(geo,
                      left_on='seller_zip_code_prefix',
                      right_on='geolocation_zip_code_prefix',
                      how='left')
        df.rename(columns={'geolocation_lat': 'seller_lat',
                            'geolocation_lng': 'seller_lng'}, inplace=True)
        df.drop(columns=['geolocation_zip_code_prefix'], inplace=True)

        # Distance
        df['distance_km'] = self._haversine(
            df['customer_lat'], df['customer_lng'],
            df['seller_lat'],   df['seller_lng'],
        )

        # Same location flags
        df['is_same_city']  = (df['customer_city']  == df['seller_city']).astype(int)
        df['is_same_state'] = (df['customer_state'] == df['seller_state']).astype(int)
        return df

"""## 8. DataMerger"""

class DataMerger:
    """Joins all datasets into a single modelling DataFrame."""

    PRODUCT_COLS = [
        'product_id', 'product_category_name',
        'product_weight_g', 'product_length_cm',
        'product_height_cm', 'product_width_cm',
    ]

    def merge(self, orders: pd.DataFrame,
              order_agg: pd.DataFrame,
              customers: pd.DataFrame,
              sellers: pd.DataFrame,
              order_items: pd.DataFrame,
              products: pd.DataFrame) -> pd.DataFrame:
        """Perform all table joins and add product volume feature."""
        df = orders.merge(order_agg, on='order_id', how='left')
        df = df.merge(customers, on='customer_id', how='left')
        df = df.merge(
            order_items[['order_id', 'product_id', 'seller_id']],
            on='order_id', how='left'
        )
        df = df.merge(sellers, on='seller_id', how='left')
        df = df.merge(products[self.PRODUCT_COLS], on='product_id', how='left')

        # Derived product features
        df['product_volume_cm3'] = (
            df['product_length_cm'] *
            df['product_height_cm'] *
            df['product_width_cm']
        )
        df.rename(columns={'product_weight_g': 'product_weight_grams'}, inplace=True)
        return df

"""## 9. DataCleaner"""

class DataCleaner:
    """Selects final features, drops NAs, and encodes categoricals."""

    FINAL_COLS = [
        'approval_delay', 'estimated_delivery_time',
        'purchase_day_of_week', 'purchase_hour',
        'total_items', 'total_price', 'total_freight_value',
        'customer_state', 'seller_state',
        'distance_km', 'is_same_city', 'is_same_state',
        'category_group', 'product_volume_cm3', 'product_weight_grams',
        'is_delayed',
    ]

    ENCODE_COLS = ['customer_state', 'seller_state', 'category_group']

    def select(self, df: pd.DataFrame) -> pd.DataFrame:
        """Keep only the modelling columns."""
        return df[self.FINAL_COLS]

    def clean(self, df: pd.DataFrame) -> pd.DataFrame:
        """Drop NAs and one-hot-encode categorical columns."""
        df = df.dropna()
        df = pd.get_dummies(df, columns=self.ENCODE_COLS, drop_first=True)
        return df

    def fit_transform(self, df: pd.DataFrame) -> pd.DataFrame:
        """Select → clean in one call."""
        df = self.select(df)
        df = self.clean(df)
        return df

"""## 10. FeatureEngineeringPipeline  *(main orchestrator)*"""

class FeatureEngineeringPipeline:
    """
    End-to-end pipeline that wires all sub-components together.

    Usage
    -----
    >>> pipeline = FeatureEngineeringPipeline()
    >>> df = pipeline.run()
    """

    def __init__(self):
        self.loader       = DataLoader()
        self.preprocessor = DataPreprocessor()
        self.order_builder = OrderFeatureBuilder()
        self.category_mapper = CategoryMapper()
        self.geo_builder  = GeoFeatureBuilder()
        self.merger       = DataMerger()
        self.cleaner      = DataCleaner()

    def run(self) -> pd.DataFrame:
        """Execute every pipeline stage and return the clean feature DataFrame."""

        # 1. Load
        print('── Step 1: Loading data …')
        data = self.loader.load()
        orders               = data['orders']
        order_items          = data['order_items']
        customers            = data['customers']
        sellers              = data['sellers']
        products             = data['products']
        geolocation          = data['geolocation']
        category_translation = data['category_translation']

        # 2. Preprocess
        print('── Step 2: Preprocessing orders …')
        orders = self.preprocessor.fit_transform(orders)

        # 3. Order-level aggregates
        print('── Step 3: Building order-level features …')
        order_agg = self.order_builder.build(order_items)

        # 4. Merge all tables
        print('── Step 4: Merging tables …')
        df = self.merger.merge(
            orders, order_agg, customers, sellers, order_items, products
        )

        # 5. Category features
        print('── Step 5: Mapping categories …')
        df = self.category_mapper.transform(df, products, category_translation)

        # 6. Geo features
        print('── Step 6: Building geo features …')
        df = self.geo_builder.build(df, geolocation)

        # 7. Select + clean
        print('── Step 7: Selecting & cleaning features …')
        df = self.cleaner.fit_transform(df)

        print(f'\n✅  Done!  Final dataset shape: {df.shape}')
        return df

"""## 11. Run the Pipeline"""

pipeline = FeatureEngineeringPipeline()
df = pipeline.run()
df.head()

"""## 12. Quick Dataset Inspection"""

print('Shape  :', df.shape)
print('Columns:', df.columns.tolist())
print('\nClass balance:')
print(df['is_delayed'].value_counts(normalize=True).round(3))
df.describe()
